apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: sales
spec:
  containers:
    - name: sales-app
      image: lucsv1/sales-app
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "0.6"
          memory: "512Mi"
        requests:
          cpu: "0.2"
          memory: "256Mi"
      volumeMounts:
        - name: meu-volume
          mountPath: /var/www/html
  volumes:
    - name: meu-volume
      emptyDir: {}
