name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: up the docker-compose
        run: docker compose up -d
      - name: configure Permissions
        run: docker compose exec app bash -c "mkdir -p /var/www/vendor && chown -R www-data:www-data /var/www"
      - name: Install Dependencies
        run: docker compose exec app composer install
      - name: Generate key
        run: docker compose exec app php artisan key:generate
      - name: Directory Permissions
        run: docker compose exec app chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: docker compose exec app php artisan test
